/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CategoryDetailResponse,
  CategorySummaryResponse,
  CreateCategoryRequest,
  DeleteRequest,
  List2Params,
  MoveCategoryRequest,
  PageCategorySummaryResponse,
  UpdateCategoryRequest,
} from "../openAPIDefinition.schemas.ts";

import { apiClient } from "../../lib/api-client.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type findById2Response200 = {
  data: CategoryDetailResponse;
  status: 200;
};

export type findById2Response404 = {
  data: CategoryDetailResponse;
  status: 404;
};

export type findById2ResponseSuccess = findById2Response200 & {
  headers: Headers;
};
export type findById2ResponseError = findById2Response404 & {
  headers: Headers;
};

export type findById2Response = findById2ResponseSuccess | findById2ResponseError;

export const getFindById2Url = (id: string) => {
  return `/api/v1/categories/${id}`;
};

/**
 * @summary カテゴリ詳細を取得する
 */
export const findById2 = async (id: string, options?: RequestInit): Promise<findById2Response> => {
  return apiClient<findById2Response>(getFindById2Url(id), {
    ...options,
    method: "GET",
  });
};

export const getFindById2QueryKey = (id: string) => {
  return [`/api/v1/categories/${id}`] as const;
};

export const getFindById2QueryOptions = <
  TData = Awaited<ReturnType<typeof findById2>>,
  TError = CategoryDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById2>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindById2QueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findById2>>> = ({ signal }) =>
    findById2(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findById2>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type FindById2QueryResult = NonNullable<Awaited<ReturnType<typeof findById2>>>;
export type FindById2QueryError = CategoryDetailResponse;

export function useFindById2<
  TData = Awaited<ReturnType<typeof findById2>>,
  TError = CategoryDetailResponse,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById2>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById2>>,
          TError,
          Awaited<ReturnType<typeof findById2>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindById2<
  TData = Awaited<ReturnType<typeof findById2>>,
  TError = CategoryDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById2>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById2>>,
          TError,
          Awaited<ReturnType<typeof findById2>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindById2<
  TData = Awaited<ReturnType<typeof findById2>>,
  TError = CategoryDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById2>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary カテゴリ詳細を取得する
 */

export function useFindById2<
  TData = Awaited<ReturnType<typeof findById2>>,
  TError = CategoryDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById2>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindById2QueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type update2Response200 = {
  data: void;
  status: 200;
};

export type update2ResponseSuccess = update2Response200 & {
  headers: Headers;
};

export type update2Response = update2ResponseSuccess;

export const getUpdate2Url = (id: string) => {
  return `/api/v1/categories/${id}`;
};

/**
 * @summary カテゴリを更新する
 */
export const update2 = async (
  id: string,
  updateCategoryRequest: UpdateCategoryRequest,
  options?: RequestInit,
): Promise<update2Response> => {
  return apiClient<update2Response>(getUpdate2Url(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateCategoryRequest),
  });
};

export const getUpdate2MutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update2>>,
    TError,
    { id: string; data: UpdateCategoryRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update2>>,
  TError,
  { id: string; data: UpdateCategoryRequest },
  TContext
> => {
  const mutationKey = ["update2"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update2>>,
    { id: string; data: UpdateCategoryRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return update2(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Update2MutationResult = NonNullable<Awaited<ReturnType<typeof update2>>>;
export type Update2MutationBody = UpdateCategoryRequest;
export type Update2MutationError = unknown;

/**
 * @summary カテゴリを更新する
 */
export const useUpdate2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update2>>,
      TError,
      { id: string; data: UpdateCategoryRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof update2>>,
  TError,
  { id: string; data: UpdateCategoryRequest },
  TContext
> => {
  return useMutation(getUpdate2MutationOptions(options), queryClient);
};
export type delete2Response204 = {
  data: void;
  status: 204;
};

export type delete2ResponseSuccess = delete2Response204 & {
  headers: Headers;
};

export type delete2Response = delete2ResponseSuccess;

export const getDelete2Url = (id: string) => {
  return `/api/v1/categories/${id}`;
};

/**
 * @summary カテゴリを削除する
 */
export const delete2 = async (
  id: string,
  deleteRequest: DeleteRequest,
  options?: RequestInit,
): Promise<delete2Response> => {
  return apiClient<delete2Response>(getDelete2Url(id), {
    ...options,
    method: "DELETE",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(deleteRequest),
  });
};

export const getDelete2MutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof delete2>>,
    TError,
    { id: string; data: DeleteRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof delete2>>,
  TError,
  { id: string; data: DeleteRequest },
  TContext
> => {
  const mutationKey = ["delete2"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof delete2>>,
    { id: string; data: DeleteRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return delete2(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Delete2MutationResult = NonNullable<Awaited<ReturnType<typeof delete2>>>;
export type Delete2MutationBody = DeleteRequest;
export type Delete2MutationError = unknown;

/**
 * @summary カテゴリを削除する
 */
export const useDelete2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof delete2>>,
      TError,
      { id: string; data: DeleteRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof delete2>>,
  TError,
  { id: string; data: DeleteRequest },
  TContext
> => {
  return useMutation(getDelete2MutationOptions(options), queryClient);
};
export type list2Response200 = {
  data: PageCategorySummaryResponse;
  status: 200;
};

export type list2ResponseSuccess = list2Response200 & {
  headers: Headers;
};

export type list2Response = list2ResponseSuccess;

export const getList2Url = (params: List2Params) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/categories?${stringifiedParams}`
    : `/api/v1/categories`;
};

/**
 * @summary ルートカテゴリ一覧を取得する
 */
export const list2 = async (params: List2Params, options?: RequestInit): Promise<list2Response> => {
  return apiClient<list2Response>(getList2Url(params), {
    ...options,
    method: "GET",
  });
};

export const getList2QueryKey = (params?: List2Params) => {
  return [`/api/v1/categories`, ...(params ? [params] : [])] as const;
};

export const getList2QueryOptions = <TData = Awaited<ReturnType<typeof list2>>, TError = unknown>(
  params: List2Params,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list2>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getList2QueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof list2>>> = ({ signal }) =>
    list2(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof list2>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type List2QueryResult = NonNullable<Awaited<ReturnType<typeof list2>>>;
export type List2QueryError = unknown;

export function useList2<TData = Awaited<ReturnType<typeof list2>>, TError = unknown>(
  params: List2Params,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof list2>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof list2>>,
          TError,
          Awaited<ReturnType<typeof list2>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useList2<TData = Awaited<ReturnType<typeof list2>>, TError = unknown>(
  params: List2Params,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list2>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof list2>>,
          TError,
          Awaited<ReturnType<typeof list2>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useList2<TData = Awaited<ReturnType<typeof list2>>, TError = unknown>(
  params: List2Params,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list2>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary ルートカテゴリ一覧を取得する
 */

export function useList2<TData = Awaited<ReturnType<typeof list2>>, TError = unknown>(
  params: List2Params,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list2>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getList2QueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type create2Response201 = {
  data: void;
  status: 201;
};

export type create2ResponseSuccess = create2Response201 & {
  headers: Headers;
};

export type create2Response = create2ResponseSuccess;

export const getCreate2Url = () => {
  return `/api/v1/categories`;
};

/**
 * @summary カテゴリを作成する
 */
export const create2 = async (
  createCategoryRequest: CreateCategoryRequest,
  options?: RequestInit,
): Promise<create2Response> => {
  return apiClient<create2Response>(getCreate2Url(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createCategoryRequest),
  });
};

export const getCreate2MutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create2>>,
    TError,
    { data: CreateCategoryRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create2>>,
  TError,
  { data: CreateCategoryRequest },
  TContext
> => {
  const mutationKey = ["create2"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create2>>,
    { data: CreateCategoryRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create2(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Create2MutationResult = NonNullable<Awaited<ReturnType<typeof create2>>>;
export type Create2MutationBody = CreateCategoryRequest;
export type Create2MutationError = unknown;

/**
 * @summary カテゴリを作成する
 */
export const useCreate2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create2>>,
      TError,
      { data: CreateCategoryRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof create2>>,
  TError,
  { data: CreateCategoryRequest },
  TContext
> => {
  return useMutation(getCreate2MutationOptions(options), queryClient);
};
export type moveResponse200 = {
  data: void;
  status: 200;
};

export type moveResponseSuccess = moveResponse200 & {
  headers: Headers;
};

export type moveResponse = moveResponseSuccess;

export const getMoveUrl = (id: string) => {
  return `/api/v1/categories/${id}/move`;
};

/**
 * @summary カテゴリを移動する
 */
export const move = async (
  id: string,
  moveCategoryRequest: MoveCategoryRequest,
  options?: RequestInit,
): Promise<moveResponse> => {
  return apiClient<moveResponse>(getMoveUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(moveCategoryRequest),
  });
};

export const getMoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof move>>,
    TError,
    { id: string; data: MoveCategoryRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof move>>,
  TError,
  { id: string; data: MoveCategoryRequest },
  TContext
> => {
  const mutationKey = ["move"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof move>>,
    { id: string; data: MoveCategoryRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return move(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MoveMutationResult = NonNullable<Awaited<ReturnType<typeof move>>>;
export type MoveMutationBody = MoveCategoryRequest;
export type MoveMutationError = unknown;

/**
 * @summary カテゴリを移動する
 */
export const useMove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof move>>,
      TError,
      { id: string; data: MoveCategoryRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof move>>,
  TError,
  { id: string; data: MoveCategoryRequest },
  TContext
> => {
  return useMutation(getMoveMutationOptions(options), queryClient);
};
export type findChildrenResponse200 = {
  data: CategorySummaryResponse[];
  status: 200;
};

export type findChildrenResponseSuccess = findChildrenResponse200 & {
  headers: Headers;
};

export type findChildrenResponse = findChildrenResponseSuccess;

export const getFindChildrenUrl = (id: string) => {
  return `/api/v1/categories/${id}/children`;
};

/**
 * @summary 直接の子カテゴリ一覧を取得する
 */
export const findChildren = async (
  id: string,
  options?: RequestInit,
): Promise<findChildrenResponse> => {
  return apiClient<findChildrenResponse>(getFindChildrenUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getFindChildrenQueryKey = (id: string) => {
  return [`/api/v1/categories/${id}/children`] as const;
};

export const getFindChildrenQueryOptions = <
  TData = Awaited<ReturnType<typeof findChildren>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findChildren>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindChildrenQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findChildren>>> = ({ signal }) =>
    findChildren(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findChildren>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type FindChildrenQueryResult = NonNullable<Awaited<ReturnType<typeof findChildren>>>;
export type FindChildrenQueryError = unknown;

export function useFindChildren<TData = Awaited<ReturnType<typeof findChildren>>, TError = unknown>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof findChildren>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findChildren>>,
          TError,
          Awaited<ReturnType<typeof findChildren>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindChildren<TData = Awaited<ReturnType<typeof findChildren>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findChildren>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findChildren>>,
          TError,
          Awaited<ReturnType<typeof findChildren>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindChildren<TData = Awaited<ReturnType<typeof findChildren>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findChildren>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 直接の子カテゴリ一覧を取得する
 */

export function useFindChildren<TData = Awaited<ReturnType<typeof findChildren>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findChildren>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindChildrenQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
