/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CategoryDetailResponse,
  CategorySummaryResponse,
  CreateCategoryRequest,
  DeleteRequest,
  ListCategoryParams,
  MoveCategoryRequest,
  PageCategorySummaryResponse,
  UpdateCategoryRequest,
} from "../openAPIDefinition.schemas.ts";

import { apiClient } from "../../lib/api-client.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type findCategoryByIdResponse200 = {
  data: CategoryDetailResponse;
  status: 200;
};

export type findCategoryByIdResponse404 = {
  data: CategoryDetailResponse;
  status: 404;
};

export type findCategoryByIdResponseSuccess = findCategoryByIdResponse200 & {
  headers: Headers;
};
export type findCategoryByIdResponseError = findCategoryByIdResponse404 & {
  headers: Headers;
};

export type findCategoryByIdResponse =
  | findCategoryByIdResponseSuccess
  | findCategoryByIdResponseError;

export const getFindCategoryByIdUrl = (id: string) => {
  return `/api/v1/categories/${id}`;
};

/**
 * @summary カテゴリ詳細を取得する
 */
export const findCategoryById = async (
  id: string,
  options?: RequestInit,
): Promise<findCategoryByIdResponse> => {
  return apiClient<findCategoryByIdResponse>(getFindCategoryByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getFindCategoryByIdQueryKey = (id: string) => {
  return [`/api/v1/categories/${id}`] as const;
};

export const getFindCategoryByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof findCategoryById>>,
  TError = CategoryDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findCategoryById>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindCategoryByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findCategoryById>>> = ({ signal }) =>
    findCategoryById(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findCategoryById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type FindCategoryByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findCategoryById>>>;
export type FindCategoryByIdQueryError = CategoryDetailResponse;

export function useFindCategoryById<
  TData = Awaited<ReturnType<typeof findCategoryById>>,
  TError = CategoryDetailResponse,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof findCategoryById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findCategoryById>>,
          TError,
          Awaited<ReturnType<typeof findCategoryById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindCategoryById<
  TData = Awaited<ReturnType<typeof findCategoryById>>,
  TError = CategoryDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findCategoryById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findCategoryById>>,
          TError,
          Awaited<ReturnType<typeof findCategoryById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindCategoryById<
  TData = Awaited<ReturnType<typeof findCategoryById>>,
  TError = CategoryDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findCategoryById>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary カテゴリ詳細を取得する
 */

export function useFindCategoryById<
  TData = Awaited<ReturnType<typeof findCategoryById>>,
  TError = CategoryDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findCategoryById>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindCategoryByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updateCategoryResponse200 = {
  data: void;
  status: 200;
};

export type updateCategoryResponseSuccess = updateCategoryResponse200 & {
  headers: Headers;
};

export type updateCategoryResponse = updateCategoryResponseSuccess;

export const getUpdateCategoryUrl = (id: string) => {
  return `/api/v1/categories/${id}`;
};

/**
 * @summary カテゴリを更新する
 */
export const updateCategory = async (
  id: string,
  updateCategoryRequest: UpdateCategoryRequest,
  options?: RequestInit,
): Promise<updateCategoryResponse> => {
  return apiClient<updateCategoryResponse>(getUpdateCategoryUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateCategoryRequest),
  });
};

export const getUpdateCategoryMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCategory>>,
    TError,
    { id: string; data: UpdateCategoryRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCategory>>,
  TError,
  { id: string; data: UpdateCategoryRequest },
  TContext
> => {
  const mutationKey = ["updateCategory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCategory>>,
    { id: string; data: UpdateCategoryRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateCategory(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof updateCategory>>>;
export type UpdateCategoryMutationBody = UpdateCategoryRequest;
export type UpdateCategoryMutationError = unknown;

/**
 * @summary カテゴリを更新する
 */
export const useUpdateCategory = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCategory>>,
      TError,
      { id: string; data: UpdateCategoryRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCategory>>,
  TError,
  { id: string; data: UpdateCategoryRequest },
  TContext
> => {
  return useMutation(getUpdateCategoryMutationOptions(options), queryClient);
};
export type deleteCategoryResponse204 = {
  data: void;
  status: 204;
};

export type deleteCategoryResponseSuccess = deleteCategoryResponse204 & {
  headers: Headers;
};

export type deleteCategoryResponse = deleteCategoryResponseSuccess;

export const getDeleteCategoryUrl = (id: string) => {
  return `/api/v1/categories/${id}`;
};

/**
 * @summary カテゴリを削除する
 */
export const deleteCategory = async (
  id: string,
  deleteRequest: DeleteRequest,
  options?: RequestInit,
): Promise<deleteCategoryResponse> => {
  return apiClient<deleteCategoryResponse>(getDeleteCategoryUrl(id), {
    ...options,
    method: "DELETE",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(deleteRequest),
  });
};

export const getDeleteCategoryMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCategory>>,
    TError,
    { id: string; data: DeleteRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCategory>>,
  TError,
  { id: string; data: DeleteRequest },
  TContext
> => {
  const mutationKey = ["deleteCategory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCategory>>,
    { id: string; data: DeleteRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return deleteCategory(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCategory>>>;
export type DeleteCategoryMutationBody = DeleteRequest;
export type DeleteCategoryMutationError = unknown;

/**
 * @summary カテゴリを削除する
 */
export const useDeleteCategory = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCategory>>,
      TError,
      { id: string; data: DeleteRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCategory>>,
  TError,
  { id: string; data: DeleteRequest },
  TContext
> => {
  return useMutation(getDeleteCategoryMutationOptions(options), queryClient);
};
export type listCategoryResponse200 = {
  data: PageCategorySummaryResponse;
  status: 200;
};

export type listCategoryResponseSuccess = listCategoryResponse200 & {
  headers: Headers;
};

export type listCategoryResponse = listCategoryResponseSuccess;

export const getListCategoryUrl = (params: ListCategoryParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/categories?${stringifiedParams}`
    : `/api/v1/categories`;
};

/**
 * @summary ルートカテゴリ一覧を取得する
 */
export const listCategory = async (
  params: ListCategoryParams,
  options?: RequestInit,
): Promise<listCategoryResponse> => {
  return apiClient<listCategoryResponse>(getListCategoryUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListCategoryQueryKey = (params?: ListCategoryParams) => {
  return [`/api/v1/categories`, ...(params ? [params] : [])] as const;
};

export const getListCategoryQueryOptions = <
  TData = Awaited<ReturnType<typeof listCategory>>,
  TError = unknown,
>(
  params: ListCategoryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listCategory>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCategoryQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCategory>>> = ({ signal }) =>
    listCategory(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCategory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListCategoryQueryResult = NonNullable<Awaited<ReturnType<typeof listCategory>>>;
export type ListCategoryQueryError = unknown;

export function useListCategory<TData = Awaited<ReturnType<typeof listCategory>>, TError = unknown>(
  params: ListCategoryParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listCategory>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCategory>>,
          TError,
          Awaited<ReturnType<typeof listCategory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListCategory<TData = Awaited<ReturnType<typeof listCategory>>, TError = unknown>(
  params: ListCategoryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listCategory>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCategory>>,
          TError,
          Awaited<ReturnType<typeof listCategory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListCategory<TData = Awaited<ReturnType<typeof listCategory>>, TError = unknown>(
  params: ListCategoryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listCategory>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary ルートカテゴリ一覧を取得する
 */

export function useListCategory<TData = Awaited<ReturnType<typeof listCategory>>, TError = unknown>(
  params: ListCategoryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listCategory>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListCategoryQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createCategoryResponse201 = {
  data: void;
  status: 201;
};

export type createCategoryResponseSuccess = createCategoryResponse201 & {
  headers: Headers;
};

export type createCategoryResponse = createCategoryResponseSuccess;

export const getCreateCategoryUrl = () => {
  return `/api/v1/categories`;
};

/**
 * @summary カテゴリを作成する
 */
export const createCategory = async (
  createCategoryRequest: CreateCategoryRequest,
  options?: RequestInit,
): Promise<createCategoryResponse> => {
  return apiClient<createCategoryResponse>(getCreateCategoryUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createCategoryRequest),
  });
};

export const getCreateCategoryMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCategory>>,
    TError,
    { data: CreateCategoryRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCategory>>,
  TError,
  { data: CreateCategoryRequest },
  TContext
> => {
  const mutationKey = ["createCategory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCategory>>,
    { data: CreateCategoryRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createCategory(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof createCategory>>>;
export type CreateCategoryMutationBody = CreateCategoryRequest;
export type CreateCategoryMutationError = unknown;

/**
 * @summary カテゴリを作成する
 */
export const useCreateCategory = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCategory>>,
      TError,
      { data: CreateCategoryRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCategory>>,
  TError,
  { data: CreateCategoryRequest },
  TContext
> => {
  return useMutation(getCreateCategoryMutationOptions(options), queryClient);
};
export type moveCategoryResponse200 = {
  data: void;
  status: 200;
};

export type moveCategoryResponseSuccess = moveCategoryResponse200 & {
  headers: Headers;
};

export type moveCategoryResponse = moveCategoryResponseSuccess;

export const getMoveCategoryUrl = (id: string) => {
  return `/api/v1/categories/${id}/move`;
};

/**
 * @summary カテゴリを移動する
 */
export const moveCategory = async (
  id: string,
  moveCategoryRequest: MoveCategoryRequest,
  options?: RequestInit,
): Promise<moveCategoryResponse> => {
  return apiClient<moveCategoryResponse>(getMoveCategoryUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(moveCategoryRequest),
  });
};

export const getMoveCategoryMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof moveCategory>>,
    TError,
    { id: string; data: MoveCategoryRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof moveCategory>>,
  TError,
  { id: string; data: MoveCategoryRequest },
  TContext
> => {
  const mutationKey = ["moveCategory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof moveCategory>>,
    { id: string; data: MoveCategoryRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return moveCategory(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MoveCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof moveCategory>>>;
export type MoveCategoryMutationBody = MoveCategoryRequest;
export type MoveCategoryMutationError = unknown;

/**
 * @summary カテゴリを移動する
 */
export const useMoveCategory = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof moveCategory>>,
      TError,
      { id: string; data: MoveCategoryRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof moveCategory>>,
  TError,
  { id: string; data: MoveCategoryRequest },
  TContext
> => {
  return useMutation(getMoveCategoryMutationOptions(options), queryClient);
};
export type findCategoryChildrenResponse200 = {
  data: CategorySummaryResponse[];
  status: 200;
};

export type findCategoryChildrenResponseSuccess = findCategoryChildrenResponse200 & {
  headers: Headers;
};

export type findCategoryChildrenResponse = findCategoryChildrenResponseSuccess;

export const getFindCategoryChildrenUrl = (id: string) => {
  return `/api/v1/categories/${id}/children`;
};

/**
 * @summary 直接の子カテゴリ一覧を取得する
 */
export const findCategoryChildren = async (
  id: string,
  options?: RequestInit,
): Promise<findCategoryChildrenResponse> => {
  return apiClient<findCategoryChildrenResponse>(getFindCategoryChildrenUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getFindCategoryChildrenQueryKey = (id: string) => {
  return [`/api/v1/categories/${id}/children`] as const;
};

export const getFindCategoryChildrenQueryOptions = <
  TData = Awaited<ReturnType<typeof findCategoryChildren>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findCategoryChildren>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindCategoryChildrenQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findCategoryChildren>>> = ({ signal }) =>
    findCategoryChildren(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findCategoryChildren>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type FindCategoryChildrenQueryResult = NonNullable<
  Awaited<ReturnType<typeof findCategoryChildren>>
>;
export type FindCategoryChildrenQueryError = unknown;

export function useFindCategoryChildren<
  TData = Awaited<ReturnType<typeof findCategoryChildren>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findCategoryChildren>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findCategoryChildren>>,
          TError,
          Awaited<ReturnType<typeof findCategoryChildren>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindCategoryChildren<
  TData = Awaited<ReturnType<typeof findCategoryChildren>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findCategoryChildren>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findCategoryChildren>>,
          TError,
          Awaited<ReturnType<typeof findCategoryChildren>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindCategoryChildren<
  TData = Awaited<ReturnType<typeof findCategoryChildren>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findCategoryChildren>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 直接の子カテゴリ一覧を取得する
 */

export function useFindCategoryChildren<
  TData = Awaited<ReturnType<typeof findCategoryChildren>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findCategoryChildren>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindCategoryChildrenQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
