/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface UpdateProductRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  /** @minLength 1 */
  categoryId: string;
  version?: number;
}

export interface UpdatePricingRequest {
  amount: number;
  validFrom: string;
  validTo?: string;
  version?: number;
}

export interface UpdateCategoryRequest {
  /**
   * @minLength 0
   * @maxLength 50
   */
  name: string;
  sortOrder?: number;
  version?: number;
}

export interface CreateProductRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  /** @minLength 1 */
  categoryId: string;
  /** @minLength 1 */
  sku: string;
}

export interface CreatePricingRequest {
  /** @minLength 1 */
  productId: string;
  /** @minLength 1 */
  level: string;
  /** @minLength 1 */
  areaCode: string;
  amount: number;
  validFrom: string;
  validTo?: string;
}

export interface CreateCategoryRequest {
  /**
   * @minLength 0
   * @maxLength 50
   */
  name: string;
  sortOrder?: number;
  parentCategoryId?: string;
}

export interface VersionRequest {
  version?: number;
}

export interface MoveCategoryRequest {
  newParentCategoryId?: string;
  version?: number;
}

export interface ProductSummaryResponse {
  id?: string;
  name?: string;
  status?: string;
  categoryId?: string;
}

export interface SortObject {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  offset?: number;
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  sort?: SortObject;
  unpaged?: boolean;
}

export interface PageProductSummaryResponse {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: ProductSummaryResponse[];
  number?: number;
  pageable?: PageableObject;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
}

export interface ProductDetailResponse {
  id?: string;
  name?: string;
  description?: string;
  categoryId?: string;
  sku?: string;
  status?: string;
  version?: number;
}

export interface PricingSummaryResponse {
  id?: string;
  productId?: string;
  level?: string;
  areaCode?: string;
  amount?: number;
}

export interface PagePricingSummaryResponse {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: PricingSummaryResponse[];
  number?: number;
  pageable?: PageableObject;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
}

export interface PricingDetailResponse {
  id?: string;
  productId?: string;
  level?: string;
  areaCode?: string;
  amount?: number;
  validFrom?: string;
  validTo?: string;
  version?: number;
}

export interface CategorySummaryResponse {
  id?: string;
  name?: string;
  sortOrder?: number;
}

export interface PageCategorySummaryResponse {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: CategorySummaryResponse[];
  number?: number;
  pageable?: PageableObject;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
}

export interface AncestorResponse {
  id?: string;
  name?: string;
}

export interface CategoryDetailResponse {
  id?: string;
  name?: string;
  sortOrder?: number;
  parentCategoryId?: string;
  version?: number;
  ancestors?: AncestorResponse[];
}

export interface DeleteRequest {
  version?: number;
}

export type ListProductParams = {
  categoryId?: string;
  status?: string;
  /**
   * Zero-based page index (0..N)
   * @minimum 0
   */
  page?: number;
  /**
   * The size of the page to be returned
   * @minimum 1
   */
  size?: number;
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[];
};

export type ListPricingParams = {
  productId?: string;
  level?: string;
  areaCode?: string;
  asOf?: string;
  /**
   * Zero-based page index (0..N)
   * @minimum 0
   */
  page?: number;
  /**
   * The size of the page to be returned
   * @minimum 1
   */
  size?: number;
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[];
};

export type ListCategoryParams = {
  /**
   * Zero-based page index (0..N)
   * @minimum 0
   */
  page?: number;
  /**
   * The size of the page to be returned
   * @minimum 1
   */
  size?: number;
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[];
};
