/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateProductRequest,
  ListProductParams,
  PageProductSummaryResponse,
  ProductDetailResponse,
  UpdateProductRequest,
  VersionRequest,
} from "../openAPIDefinition.schemas.ts";

import { apiClient } from "../../lib/api-client.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type findProductByIdResponse200 = {
  data: ProductDetailResponse;
  status: 200;
};

export type findProductByIdResponse404 = {
  data: ProductDetailResponse;
  status: 404;
};

export type findProductByIdResponseSuccess = findProductByIdResponse200 & {
  headers: Headers;
};
export type findProductByIdResponseError = findProductByIdResponse404 & {
  headers: Headers;
};

export type findProductByIdResponse = findProductByIdResponseSuccess | findProductByIdResponseError;

export const getFindProductByIdUrl = (id: string) => {
  return `/api/v1/products/${id}`;
};

/**
 * @summary 商品詳細を取得する
 */
export const findProductById = async (
  id: string,
  options?: RequestInit,
): Promise<findProductByIdResponse> => {
  return apiClient<findProductByIdResponse>(getFindProductByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getFindProductByIdQueryKey = (id: string) => {
  return [`/api/v1/products/${id}`] as const;
};

export const getFindProductByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof findProductById>>,
  TError = ProductDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findProductById>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindProductByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findProductById>>> = ({ signal }) =>
    findProductById(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findProductById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type FindProductByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findProductById>>>;
export type FindProductByIdQueryError = ProductDetailResponse;

export function useFindProductById<
  TData = Awaited<ReturnType<typeof findProductById>>,
  TError = ProductDetailResponse,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof findProductById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findProductById>>,
          TError,
          Awaited<ReturnType<typeof findProductById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindProductById<
  TData = Awaited<ReturnType<typeof findProductById>>,
  TError = ProductDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findProductById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findProductById>>,
          TError,
          Awaited<ReturnType<typeof findProductById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindProductById<
  TData = Awaited<ReturnType<typeof findProductById>>,
  TError = ProductDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findProductById>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 商品詳細を取得する
 */

export function useFindProductById<
  TData = Awaited<ReturnType<typeof findProductById>>,
  TError = ProductDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findProductById>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindProductByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updateProductResponse200 = {
  data: void;
  status: 200;
};

export type updateProductResponseSuccess = updateProductResponse200 & {
  headers: Headers;
};

export type updateProductResponse = updateProductResponseSuccess;

export const getUpdateProductUrl = (id: string) => {
  return `/api/v1/products/${id}`;
};

/**
 * @summary 商品を更新する
 */
export const updateProduct = async (
  id: string,
  updateProductRequest: UpdateProductRequest,
  options?: RequestInit,
): Promise<updateProductResponse> => {
  return apiClient<updateProductResponse>(getUpdateProductUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProductRequest),
  });
};

export const getUpdateProductMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProduct>>,
    TError,
    { id: string; data: UpdateProductRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProduct>>,
  TError,
  { id: string; data: UpdateProductRequest },
  TContext
> => {
  const mutationKey = ["updateProduct"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProduct>>,
    { id: string; data: UpdateProductRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateProduct(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProductMutationResult = NonNullable<Awaited<ReturnType<typeof updateProduct>>>;
export type UpdateProductMutationBody = UpdateProductRequest;
export type UpdateProductMutationError = unknown;

/**
 * @summary 商品を更新する
 */
export const useUpdateProduct = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProduct>>,
      TError,
      { id: string; data: UpdateProductRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateProduct>>,
  TError,
  { id: string; data: UpdateProductRequest },
  TContext
> => {
  return useMutation(getUpdateProductMutationOptions(options), queryClient);
};
export type deleteProductResponse204 = {
  data: void;
  status: 204;
};

export type deleteProductResponseSuccess = deleteProductResponse204 & {
  headers: Headers;
};

export type deleteProductResponse = deleteProductResponseSuccess;

export const getDeleteProductUrl = (id: string) => {
  return `/api/v1/products/${id}`;
};

/**
 * @summary 商品を削除する
 */
export const deleteProduct = async (
  id: string,
  versionRequest: VersionRequest,
  options?: RequestInit,
): Promise<deleteProductResponse> => {
  return apiClient<deleteProductResponse>(getDeleteProductUrl(id), {
    ...options,
    method: "DELETE",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(versionRequest),
  });
};

export const getDeleteProductMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteProduct>>,
    TError,
    { id: string; data: VersionRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteProduct>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  const mutationKey = ["deleteProduct"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteProduct>>,
    { id: string; data: VersionRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return deleteProduct(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteProductMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProduct>>>;
export type DeleteProductMutationBody = VersionRequest;
export type DeleteProductMutationError = unknown;

/**
 * @summary 商品を削除する
 */
export const useDeleteProduct = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteProduct>>,
      TError,
      { id: string; data: VersionRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteProduct>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  return useMutation(getDeleteProductMutationOptions(options), queryClient);
};
export type listProductResponse200 = {
  data: PageProductSummaryResponse;
  status: 200;
};

export type listProductResponseSuccess = listProductResponse200 & {
  headers: Headers;
};

export type listProductResponse = listProductResponseSuccess;

export const getListProductUrl = (params: ListProductParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/products?${stringifiedParams}`
    : `/api/v1/products`;
};

/**
 * @summary 商品一覧を取得する
 */
export const listProduct = async (
  params: ListProductParams,
  options?: RequestInit,
): Promise<listProductResponse> => {
  return apiClient<listProductResponse>(getListProductUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListProductQueryKey = (params?: ListProductParams) => {
  return [`/api/v1/products`, ...(params ? [params] : [])] as const;
};

export const getListProductQueryOptions = <
  TData = Awaited<ReturnType<typeof listProduct>>,
  TError = unknown,
>(
  params: ListProductParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listProduct>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListProductQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listProduct>>> = ({ signal }) =>
    listProduct(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listProduct>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListProductQueryResult = NonNullable<Awaited<ReturnType<typeof listProduct>>>;
export type ListProductQueryError = unknown;

export function useListProduct<TData = Awaited<ReturnType<typeof listProduct>>, TError = unknown>(
  params: ListProductParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listProduct>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProduct>>,
          TError,
          Awaited<ReturnType<typeof listProduct>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListProduct<TData = Awaited<ReturnType<typeof listProduct>>, TError = unknown>(
  params: ListProductParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listProduct>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProduct>>,
          TError,
          Awaited<ReturnType<typeof listProduct>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListProduct<TData = Awaited<ReturnType<typeof listProduct>>, TError = unknown>(
  params: ListProductParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listProduct>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 商品一覧を取得する
 */

export function useListProduct<TData = Awaited<ReturnType<typeof listProduct>>, TError = unknown>(
  params: ListProductParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listProduct>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListProductQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createProductResponse201 = {
  data: void;
  status: 201;
};

export type createProductResponseSuccess = createProductResponse201 & {
  headers: Headers;
};

export type createProductResponse = createProductResponseSuccess;

export const getCreateProductUrl = () => {
  return `/api/v1/products`;
};

/**
 * @summary 商品を作成する
 */
export const createProduct = async (
  createProductRequest: CreateProductRequest,
  options?: RequestInit,
): Promise<createProductResponse> => {
  return apiClient<createProductResponse>(getCreateProductUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createProductRequest),
  });
};

export const getCreateProductMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProduct>>,
    TError,
    { data: CreateProductRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProduct>>,
  TError,
  { data: CreateProductRequest },
  TContext
> => {
  const mutationKey = ["createProduct"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProduct>>,
    { data: CreateProductRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createProduct(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateProductMutationResult = NonNullable<Awaited<ReturnType<typeof createProduct>>>;
export type CreateProductMutationBody = CreateProductRequest;
export type CreateProductMutationError = unknown;

/**
 * @summary 商品を作成する
 */
export const useCreateProduct = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createProduct>>,
      TError,
      { data: CreateProductRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createProduct>>,
  TError,
  { data: CreateProductRequest },
  TContext
> => {
  return useMutation(getCreateProductMutationOptions(options), queryClient);
};
export type unpublishProductResponse200 = {
  data: void;
  status: 200;
};

export type unpublishProductResponseSuccess = unpublishProductResponse200 & {
  headers: Headers;
};

export type unpublishProductResponse = unpublishProductResponseSuccess;

export const getUnpublishProductUrl = (id: string) => {
  return `/api/v1/products/${id}/unpublish`;
};

/**
 * @summary 商品を非公開にする
 */
export const unpublishProduct = async (
  id: string,
  versionRequest: VersionRequest,
  options?: RequestInit,
): Promise<unpublishProductResponse> => {
  return apiClient<unpublishProductResponse>(getUnpublishProductUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(versionRequest),
  });
};

export const getUnpublishProductMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unpublishProduct>>,
    TError,
    { id: string; data: VersionRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unpublishProduct>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  const mutationKey = ["unpublishProduct"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unpublishProduct>>,
    { id: string; data: VersionRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return unpublishProduct(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnpublishProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof unpublishProduct>>
>;
export type UnpublishProductMutationBody = VersionRequest;
export type UnpublishProductMutationError = unknown;

/**
 * @summary 商品を非公開にする
 */
export const useUnpublishProduct = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unpublishProduct>>,
      TError,
      { id: string; data: VersionRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof unpublishProduct>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  return useMutation(getUnpublishProductMutationOptions(options), queryClient);
};
export type publishProductResponse200 = {
  data: void;
  status: 200;
};

export type publishProductResponseSuccess = publishProductResponse200 & {
  headers: Headers;
};

export type publishProductResponse = publishProductResponseSuccess;

export const getPublishProductUrl = (id: string) => {
  return `/api/v1/products/${id}/publish`;
};

/**
 * @summary 商品を公開する
 */
export const publishProduct = async (
  id: string,
  versionRequest: VersionRequest,
  options?: RequestInit,
): Promise<publishProductResponse> => {
  return apiClient<publishProductResponse>(getPublishProductUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(versionRequest),
  });
};

export const getPublishProductMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof publishProduct>>,
    TError,
    { id: string; data: VersionRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof publishProduct>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  const mutationKey = ["publishProduct"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof publishProduct>>,
    { id: string; data: VersionRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return publishProduct(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PublishProductMutationResult = NonNullable<Awaited<ReturnType<typeof publishProduct>>>;
export type PublishProductMutationBody = VersionRequest;
export type PublishProductMutationError = unknown;

/**
 * @summary 商品を公開する
 */
export const usePublishProduct = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof publishProduct>>,
      TError,
      { id: string; data: VersionRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof publishProduct>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  return useMutation(getPublishProductMutationOptions(options), queryClient);
};
export type archiveProductResponse200 = {
  data: void;
  status: 200;
};

export type archiveProductResponseSuccess = archiveProductResponse200 & {
  headers: Headers;
};

export type archiveProductResponse = archiveProductResponseSuccess;

export const getArchiveProductUrl = (id: string) => {
  return `/api/v1/products/${id}/archive`;
};

/**
 * @summary 商品をアーカイブする
 */
export const archiveProduct = async (
  id: string,
  versionRequest: VersionRequest,
  options?: RequestInit,
): Promise<archiveProductResponse> => {
  return apiClient<archiveProductResponse>(getArchiveProductUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(versionRequest),
  });
};

export const getArchiveProductMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof archiveProduct>>,
    TError,
    { id: string; data: VersionRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof archiveProduct>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  const mutationKey = ["archiveProduct"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof archiveProduct>>,
    { id: string; data: VersionRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return archiveProduct(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ArchiveProductMutationResult = NonNullable<Awaited<ReturnType<typeof archiveProduct>>>;
export type ArchiveProductMutationBody = VersionRequest;
export type ArchiveProductMutationError = unknown;

/**
 * @summary 商品をアーカイブする
 */
export const useArchiveProduct = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof archiveProduct>>,
      TError,
      { id: string; data: VersionRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof archiveProduct>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  return useMutation(getArchiveProductMutationOptions(options), queryClient);
};
