/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateProductRequest,
  ListParams,
  PageProductSummaryResponse,
  ProductDetailResponse,
  UpdateProductRequest,
  VersionRequest,
} from "../openAPIDefinition.schemas.ts";

import { apiClient } from "../../lib/api-client.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type findByIdResponse200 = {
  data: ProductDetailResponse;
  status: 200;
};

export type findByIdResponse404 = {
  data: ProductDetailResponse;
  status: 404;
};

export type findByIdResponseSuccess = findByIdResponse200 & {
  headers: Headers;
};
export type findByIdResponseError = findByIdResponse404 & {
  headers: Headers;
};

export type findByIdResponse = findByIdResponseSuccess | findByIdResponseError;

export const getFindByIdUrl = (id: string) => {
  return `/api/v1/products/${id}`;
};

/**
 * @summary 商品詳細を取得する
 */
export const findById = async (id: string, options?: RequestInit): Promise<findByIdResponse> => {
  return apiClient<findByIdResponse>(getFindByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getFindByIdQueryKey = (id: string) => {
  return [`/api/v1/products/${id}`] as const;
};

export const getFindByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof findById>>,
  TError = ProductDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findById>>> = ({ signal }) =>
    findById(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type FindByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findById>>>;
export type FindByIdQueryError = ProductDetailResponse;

export function useFindById<
  TData = Awaited<ReturnType<typeof findById>>,
  TError = ProductDetailResponse,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById>>,
          TError,
          Awaited<ReturnType<typeof findById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindById<
  TData = Awaited<ReturnType<typeof findById>>,
  TError = ProductDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById>>,
          TError,
          Awaited<ReturnType<typeof findById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindById<
  TData = Awaited<ReturnType<typeof findById>>,
  TError = ProductDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 商品詳細を取得する
 */

export function useFindById<
  TData = Awaited<ReturnType<typeof findById>>,
  TError = ProductDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updateResponse200 = {
  data: void;
  status: 200;
};

export type updateResponseSuccess = updateResponse200 & {
  headers: Headers;
};

export type updateResponse = updateResponseSuccess;

export const getUpdateUrl = (id: string) => {
  return `/api/v1/products/${id}`;
};

/**
 * @summary 商品を更新する
 */
export const update = async (
  id: string,
  updateProductRequest: UpdateProductRequest,
  options?: RequestInit,
): Promise<updateResponse> => {
  return apiClient<updateResponse>(getUpdateUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProductRequest),
  });
};

export const getUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update>>,
    TError,
    { id: string; data: UpdateProductRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update>>,
  TError,
  { id: string; data: UpdateProductRequest },
  TContext
> => {
  const mutationKey = ["update"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update>>,
    { id: string; data: UpdateProductRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return update(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMutationResult = NonNullable<Awaited<ReturnType<typeof update>>>;
export type UpdateMutationBody = UpdateProductRequest;
export type UpdateMutationError = unknown;

/**
 * @summary 商品を更新する
 */
export const useUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update>>,
      TError,
      { id: string; data: UpdateProductRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof update>>,
  TError,
  { id: string; data: UpdateProductRequest },
  TContext
> => {
  return useMutation(getUpdateMutationOptions(options), queryClient);
};
export type _deleteResponse204 = {
  data: void;
  status: 204;
};

export type _deleteResponseSuccess = _deleteResponse204 & {
  headers: Headers;
};

export type _deleteResponse = _deleteResponseSuccess;

export const getDeleteUrl = (id: string) => {
  return `/api/v1/products/${id}`;
};

/**
 * @summary 商品を削除する
 */
export const _delete = async (
  id: string,
  versionRequest: VersionRequest,
  options?: RequestInit,
): Promise<_deleteResponse> => {
  return apiClient<_deleteResponse>(getDeleteUrl(id), {
    ...options,
    method: "DELETE",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(versionRequest),
  });
};

export const getDeleteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof _delete>>,
    TError,
    { id: string; data: VersionRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof _delete>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  const mutationKey = ["_delete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof _delete>>,
    { id: string; data: VersionRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return _delete(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type _DeleteMutationResult = NonNullable<Awaited<ReturnType<typeof _delete>>>;
export type _DeleteMutationBody = VersionRequest;
export type _DeleteMutationError = unknown;

/**
 * @summary 商品を削除する
 */
export const useDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof _delete>>,
      TError,
      { id: string; data: VersionRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof _delete>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  return useMutation(getDeleteMutationOptions(options), queryClient);
};
export type listResponse200 = {
  data: PageProductSummaryResponse;
  status: 200;
};

export type listResponseSuccess = listResponse200 & {
  headers: Headers;
};

export type listResponse = listResponseSuccess;

export const getListUrl = (params: ListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/products?${stringifiedParams}`
    : `/api/v1/products`;
};

/**
 * @summary 商品一覧を取得する
 */
export const list = async (params: ListParams, options?: RequestInit): Promise<listResponse> => {
  return apiClient<listResponse>(getListUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListQueryKey = (params?: ListParams) => {
  return [`/api/v1/products`, ...(params ? [params] : [])] as const;
};

export const getListQueryOptions = <TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  params: ListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof list>>> = ({ signal }) =>
    list(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof list>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListQueryResult = NonNullable<Awaited<ReturnType<typeof list>>>;
export type ListQueryError = unknown;

export function useList<TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  params: ListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof list>>,
          TError,
          Awaited<ReturnType<typeof list>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useList<TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  params: ListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof list>>,
          TError,
          Awaited<ReturnType<typeof list>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useList<TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  params: ListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 商品一覧を取得する
 */

export function useList<TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  params: ListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createResponse201 = {
  data: void;
  status: 201;
};

export type createResponseSuccess = createResponse201 & {
  headers: Headers;
};

export type createResponse = createResponseSuccess;

export const getCreateUrl = () => {
  return `/api/v1/products`;
};

/**
 * @summary 商品を作成する
 */
export const create = async (
  createProductRequest: CreateProductRequest,
  options?: RequestInit,
): Promise<createResponse> => {
  return apiClient<createResponse>(getCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createProductRequest),
  });
};

export const getCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create>>,
    TError,
    { data: CreateProductRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create>>,
  TError,
  { data: CreateProductRequest },
  TContext
> => {
  const mutationKey = ["create"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create>>,
    { data: CreateProductRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMutationResult = NonNullable<Awaited<ReturnType<typeof create>>>;
export type CreateMutationBody = CreateProductRequest;
export type CreateMutationError = unknown;

/**
 * @summary 商品を作成する
 */
export const useCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create>>,
      TError,
      { data: CreateProductRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof create>>,
  TError,
  { data: CreateProductRequest },
  TContext
> => {
  return useMutation(getCreateMutationOptions(options), queryClient);
};
export type unpublishResponse200 = {
  data: void;
  status: 200;
};

export type unpublishResponseSuccess = unpublishResponse200 & {
  headers: Headers;
};

export type unpublishResponse = unpublishResponseSuccess;

export const getUnpublishUrl = (id: string) => {
  return `/api/v1/products/${id}/unpublish`;
};

/**
 * @summary 商品を非公開にする
 */
export const unpublish = async (
  id: string,
  versionRequest: VersionRequest,
  options?: RequestInit,
): Promise<unpublishResponse> => {
  return apiClient<unpublishResponse>(getUnpublishUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(versionRequest),
  });
};

export const getUnpublishMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unpublish>>,
    TError,
    { id: string; data: VersionRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unpublish>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  const mutationKey = ["unpublish"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unpublish>>,
    { id: string; data: VersionRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return unpublish(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnpublishMutationResult = NonNullable<Awaited<ReturnType<typeof unpublish>>>;
export type UnpublishMutationBody = VersionRequest;
export type UnpublishMutationError = unknown;

/**
 * @summary 商品を非公開にする
 */
export const useUnpublish = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unpublish>>,
      TError,
      { id: string; data: VersionRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof unpublish>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  return useMutation(getUnpublishMutationOptions(options), queryClient);
};
export type publishResponse200 = {
  data: void;
  status: 200;
};

export type publishResponseSuccess = publishResponse200 & {
  headers: Headers;
};

export type publishResponse = publishResponseSuccess;

export const getPublishUrl = (id: string) => {
  return `/api/v1/products/${id}/publish`;
};

/**
 * @summary 商品を公開する
 */
export const publish = async (
  id: string,
  versionRequest: VersionRequest,
  options?: RequestInit,
): Promise<publishResponse> => {
  return apiClient<publishResponse>(getPublishUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(versionRequest),
  });
};

export const getPublishMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof publish>>,
    TError,
    { id: string; data: VersionRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof publish>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  const mutationKey = ["publish"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof publish>>,
    { id: string; data: VersionRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return publish(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PublishMutationResult = NonNullable<Awaited<ReturnType<typeof publish>>>;
export type PublishMutationBody = VersionRequest;
export type PublishMutationError = unknown;

/**
 * @summary 商品を公開する
 */
export const usePublish = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof publish>>,
      TError,
      { id: string; data: VersionRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof publish>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  return useMutation(getPublishMutationOptions(options), queryClient);
};
export type archiveResponse200 = {
  data: void;
  status: 200;
};

export type archiveResponseSuccess = archiveResponse200 & {
  headers: Headers;
};

export type archiveResponse = archiveResponseSuccess;

export const getArchiveUrl = (id: string) => {
  return `/api/v1/products/${id}/archive`;
};

/**
 * @summary 商品をアーカイブする
 */
export const archive = async (
  id: string,
  versionRequest: VersionRequest,
  options?: RequestInit,
): Promise<archiveResponse> => {
  return apiClient<archiveResponse>(getArchiveUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(versionRequest),
  });
};

export const getArchiveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof archive>>,
    TError,
    { id: string; data: VersionRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof archive>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  const mutationKey = ["archive"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof archive>>,
    { id: string; data: VersionRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return archive(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ArchiveMutationResult = NonNullable<Awaited<ReturnType<typeof archive>>>;
export type ArchiveMutationBody = VersionRequest;
export type ArchiveMutationError = unknown;

/**
 * @summary 商品をアーカイブする
 */
export const useArchive = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof archive>>,
      TError,
      { id: string; data: VersionRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof archive>>,
  TError,
  { id: string; data: VersionRequest },
  TContext
> => {
  return useMutation(getArchiveMutationOptions(options), queryClient);
};
