/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreatePricingRequest,
  DeleteRequest,
  List1Params,
  PagePricingSummaryResponse,
  PricingDetailResponse,
  UpdatePricingRequest,
} from "../openAPIDefinition.schemas.ts";

import { apiClient } from "../../lib/api-client.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type findById1Response200 = {
  data: PricingDetailResponse;
  status: 200;
};

export type findById1Response404 = {
  data: PricingDetailResponse;
  status: 404;
};

export type findById1ResponseSuccess = findById1Response200 & {
  headers: Headers;
};
export type findById1ResponseError = findById1Response404 & {
  headers: Headers;
};

export type findById1Response = findById1ResponseSuccess | findById1ResponseError;

export const getFindById1Url = (id: string) => {
  return `/api/v1/pricings/${id}`;
};

/**
 * @summary 価格詳細を取得する
 */
export const findById1 = async (id: string, options?: RequestInit): Promise<findById1Response> => {
  return apiClient<findById1Response>(getFindById1Url(id), {
    ...options,
    method: "GET",
  });
};

export const getFindById1QueryKey = (id: string) => {
  return [`/api/v1/pricings/${id}`] as const;
};

export const getFindById1QueryOptions = <
  TData = Awaited<ReturnType<typeof findById1>>,
  TError = PricingDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById1>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindById1QueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findById1>>> = ({ signal }) =>
    findById1(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findById1>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type FindById1QueryResult = NonNullable<Awaited<ReturnType<typeof findById1>>>;
export type FindById1QueryError = PricingDetailResponse;

export function useFindById1<
  TData = Awaited<ReturnType<typeof findById1>>,
  TError = PricingDetailResponse,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById1>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById1>>,
          TError,
          Awaited<ReturnType<typeof findById1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindById1<
  TData = Awaited<ReturnType<typeof findById1>>,
  TError = PricingDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById1>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById1>>,
          TError,
          Awaited<ReturnType<typeof findById1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindById1<
  TData = Awaited<ReturnType<typeof findById1>>,
  TError = PricingDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById1>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 価格詳細を取得する
 */

export function useFindById1<
  TData = Awaited<ReturnType<typeof findById1>>,
  TError = PricingDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findById1>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindById1QueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type update1Response200 = {
  data: void;
  status: 200;
};

export type update1ResponseSuccess = update1Response200 & {
  headers: Headers;
};

export type update1Response = update1ResponseSuccess;

export const getUpdate1Url = (id: string) => {
  return `/api/v1/pricings/${id}`;
};

/**
 * @summary 価格を更新する
 */
export const update1 = async (
  id: string,
  updatePricingRequest: UpdatePricingRequest,
  options?: RequestInit,
): Promise<update1Response> => {
  return apiClient<update1Response>(getUpdate1Url(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updatePricingRequest),
  });
};

export const getUpdate1MutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update1>>,
    TError,
    { id: string; data: UpdatePricingRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update1>>,
  TError,
  { id: string; data: UpdatePricingRequest },
  TContext
> => {
  const mutationKey = ["update1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update1>>,
    { id: string; data: UpdatePricingRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return update1(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Update1MutationResult = NonNullable<Awaited<ReturnType<typeof update1>>>;
export type Update1MutationBody = UpdatePricingRequest;
export type Update1MutationError = unknown;

/**
 * @summary 価格を更新する
 */
export const useUpdate1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update1>>,
      TError,
      { id: string; data: UpdatePricingRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof update1>>,
  TError,
  { id: string; data: UpdatePricingRequest },
  TContext
> => {
  return useMutation(getUpdate1MutationOptions(options), queryClient);
};
export type delete1Response204 = {
  data: void;
  status: 204;
};

export type delete1ResponseSuccess = delete1Response204 & {
  headers: Headers;
};

export type delete1Response = delete1ResponseSuccess;

export const getDelete1Url = (id: string) => {
  return `/api/v1/pricings/${id}`;
};

/**
 * @summary 価格を削除する
 */
export const delete1 = async (
  id: string,
  deleteRequest: DeleteRequest,
  options?: RequestInit,
): Promise<delete1Response> => {
  return apiClient<delete1Response>(getDelete1Url(id), {
    ...options,
    method: "DELETE",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(deleteRequest),
  });
};

export const getDelete1MutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof delete1>>,
    TError,
    { id: string; data: DeleteRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof delete1>>,
  TError,
  { id: string; data: DeleteRequest },
  TContext
> => {
  const mutationKey = ["delete1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof delete1>>,
    { id: string; data: DeleteRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return delete1(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Delete1MutationResult = NonNullable<Awaited<ReturnType<typeof delete1>>>;
export type Delete1MutationBody = DeleteRequest;
export type Delete1MutationError = unknown;

/**
 * @summary 価格を削除する
 */
export const useDelete1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof delete1>>,
      TError,
      { id: string; data: DeleteRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof delete1>>,
  TError,
  { id: string; data: DeleteRequest },
  TContext
> => {
  return useMutation(getDelete1MutationOptions(options), queryClient);
};
export type list1Response200 = {
  data: PagePricingSummaryResponse;
  status: 200;
};

export type list1ResponseSuccess = list1Response200 & {
  headers: Headers;
};

export type list1Response = list1ResponseSuccess;

export const getList1Url = (params: List1Params) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/pricings?${stringifiedParams}`
    : `/api/v1/pricings`;
};

/**
 * @summary 価格一覧を取得する
 */
export const list1 = async (params: List1Params, options?: RequestInit): Promise<list1Response> => {
  return apiClient<list1Response>(getList1Url(params), {
    ...options,
    method: "GET",
  });
};

export const getList1QueryKey = (params?: List1Params) => {
  return [`/api/v1/pricings`, ...(params ? [params] : [])] as const;
};

export const getList1QueryOptions = <TData = Awaited<ReturnType<typeof list1>>, TError = unknown>(
  params: List1Params,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list1>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getList1QueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof list1>>> = ({ signal }) =>
    list1(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof list1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type List1QueryResult = NonNullable<Awaited<ReturnType<typeof list1>>>;
export type List1QueryError = unknown;

export function useList1<TData = Awaited<ReturnType<typeof list1>>, TError = unknown>(
  params: List1Params,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof list1>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof list1>>,
          TError,
          Awaited<ReturnType<typeof list1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useList1<TData = Awaited<ReturnType<typeof list1>>, TError = unknown>(
  params: List1Params,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list1>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof list1>>,
          TError,
          Awaited<ReturnType<typeof list1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useList1<TData = Awaited<ReturnType<typeof list1>>, TError = unknown>(
  params: List1Params,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list1>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 価格一覧を取得する
 */

export function useList1<TData = Awaited<ReturnType<typeof list1>>, TError = unknown>(
  params: List1Params,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list1>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getList1QueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type create1Response201 = {
  data: void;
  status: 201;
};

export type create1ResponseSuccess = create1Response201 & {
  headers: Headers;
};

export type create1Response = create1ResponseSuccess;

export const getCreate1Url = () => {
  return `/api/v1/pricings`;
};

/**
 * @summary 価格を作成する
 */
export const create1 = async (
  createPricingRequest: CreatePricingRequest,
  options?: RequestInit,
): Promise<create1Response> => {
  return apiClient<create1Response>(getCreate1Url(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createPricingRequest),
  });
};

export const getCreate1MutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create1>>,
    TError,
    { data: CreatePricingRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create1>>,
  TError,
  { data: CreatePricingRequest },
  TContext
> => {
  const mutationKey = ["create1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create1>>,
    { data: CreatePricingRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Create1MutationResult = NonNullable<Awaited<ReturnType<typeof create1>>>;
export type Create1MutationBody = CreatePricingRequest;
export type Create1MutationError = unknown;

/**
 * @summary 価格を作成する
 */
export const useCreate1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create1>>,
      TError,
      { data: CreatePricingRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof create1>>,
  TError,
  { data: CreatePricingRequest },
  TContext
> => {
  return useMutation(getCreate1MutationOptions(options), queryClient);
};
