/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreatePricingRequest,
  DeleteRequest,
  ListPricingParams,
  PagePricingSummaryResponse,
  PricingDetailResponse,
  UpdatePricingRequest,
} from "../openAPIDefinition.schemas.ts";

import { apiClient } from "../../lib/api-client.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type findPricingByIdResponse200 = {
  data: PricingDetailResponse;
  status: 200;
};

export type findPricingByIdResponse404 = {
  data: PricingDetailResponse;
  status: 404;
};

export type findPricingByIdResponseSuccess = findPricingByIdResponse200 & {
  headers: Headers;
};
export type findPricingByIdResponseError = findPricingByIdResponse404 & {
  headers: Headers;
};

export type findPricingByIdResponse = findPricingByIdResponseSuccess | findPricingByIdResponseError;

export const getFindPricingByIdUrl = (id: string) => {
  return `/api/v1/pricings/${id}`;
};

/**
 * @summary 価格詳細を取得する
 */
export const findPricingById = async (
  id: string,
  options?: RequestInit,
): Promise<findPricingByIdResponse> => {
  return apiClient<findPricingByIdResponse>(getFindPricingByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getFindPricingByIdQueryKey = (id: string) => {
  return [`/api/v1/pricings/${id}`] as const;
};

export const getFindPricingByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof findPricingById>>,
  TError = PricingDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findPricingById>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindPricingByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findPricingById>>> = ({ signal }) =>
    findPricingById(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findPricingById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type FindPricingByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findPricingById>>>;
export type FindPricingByIdQueryError = PricingDetailResponse;

export function useFindPricingById<
  TData = Awaited<ReturnType<typeof findPricingById>>,
  TError = PricingDetailResponse,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof findPricingById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findPricingById>>,
          TError,
          Awaited<ReturnType<typeof findPricingById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindPricingById<
  TData = Awaited<ReturnType<typeof findPricingById>>,
  TError = PricingDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findPricingById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findPricingById>>,
          TError,
          Awaited<ReturnType<typeof findPricingById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindPricingById<
  TData = Awaited<ReturnType<typeof findPricingById>>,
  TError = PricingDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findPricingById>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 価格詳細を取得する
 */

export function useFindPricingById<
  TData = Awaited<ReturnType<typeof findPricingById>>,
  TError = PricingDetailResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findPricingById>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindPricingByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updatePricingResponse200 = {
  data: void;
  status: 200;
};

export type updatePricingResponseSuccess = updatePricingResponse200 & {
  headers: Headers;
};

export type updatePricingResponse = updatePricingResponseSuccess;

export const getUpdatePricingUrl = (id: string) => {
  return `/api/v1/pricings/${id}`;
};

/**
 * @summary 価格を更新する
 */
export const updatePricing = async (
  id: string,
  updatePricingRequest: UpdatePricingRequest,
  options?: RequestInit,
): Promise<updatePricingResponse> => {
  return apiClient<updatePricingResponse>(getUpdatePricingUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updatePricingRequest),
  });
};

export const getUpdatePricingMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePricing>>,
    TError,
    { id: string; data: UpdatePricingRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePricing>>,
  TError,
  { id: string; data: UpdatePricingRequest },
  TContext
> => {
  const mutationKey = ["updatePricing"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePricing>>,
    { id: string; data: UpdatePricingRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updatePricing(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePricingMutationResult = NonNullable<Awaited<ReturnType<typeof updatePricing>>>;
export type UpdatePricingMutationBody = UpdatePricingRequest;
export type UpdatePricingMutationError = unknown;

/**
 * @summary 価格を更新する
 */
export const useUpdatePricing = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePricing>>,
      TError,
      { id: string; data: UpdatePricingRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePricing>>,
  TError,
  { id: string; data: UpdatePricingRequest },
  TContext
> => {
  return useMutation(getUpdatePricingMutationOptions(options), queryClient);
};
export type deletePricingResponse204 = {
  data: void;
  status: 204;
};

export type deletePricingResponseSuccess = deletePricingResponse204 & {
  headers: Headers;
};

export type deletePricingResponse = deletePricingResponseSuccess;

export const getDeletePricingUrl = (id: string) => {
  return `/api/v1/pricings/${id}`;
};

/**
 * @summary 価格を削除する
 */
export const deletePricing = async (
  id: string,
  deleteRequest: DeleteRequest,
  options?: RequestInit,
): Promise<deletePricingResponse> => {
  return apiClient<deletePricingResponse>(getDeletePricingUrl(id), {
    ...options,
    method: "DELETE",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(deleteRequest),
  });
};

export const getDeletePricingMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePricing>>,
    TError,
    { id: string; data: DeleteRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePricing>>,
  TError,
  { id: string; data: DeleteRequest },
  TContext
> => {
  const mutationKey = ["deletePricing"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePricing>>,
    { id: string; data: DeleteRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return deletePricing(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePricingMutationResult = NonNullable<Awaited<ReturnType<typeof deletePricing>>>;
export type DeletePricingMutationBody = DeleteRequest;
export type DeletePricingMutationError = unknown;

/**
 * @summary 価格を削除する
 */
export const useDeletePricing = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePricing>>,
      TError,
      { id: string; data: DeleteRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePricing>>,
  TError,
  { id: string; data: DeleteRequest },
  TContext
> => {
  return useMutation(getDeletePricingMutationOptions(options), queryClient);
};
export type listPricingResponse200 = {
  data: PagePricingSummaryResponse;
  status: 200;
};

export type listPricingResponseSuccess = listPricingResponse200 & {
  headers: Headers;
};

export type listPricingResponse = listPricingResponseSuccess;

export const getListPricingUrl = (params?: ListPricingParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/pricings?${stringifiedParams}`
    : `/api/v1/pricings`;
};

/**
 * @summary 価格一覧を取得する
 */
export const listPricing = async (
  params?: ListPricingParams,
  options?: RequestInit,
): Promise<listPricingResponse> => {
  return apiClient<listPricingResponse>(getListPricingUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListPricingQueryKey = (params?: ListPricingParams) => {
  return [`/api/v1/pricings`, ...(params ? [params] : [])] as const;
};

export const getListPricingQueryOptions = <
  TData = Awaited<ReturnType<typeof listPricing>>,
  TError = unknown,
>(
  params?: ListPricingParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPricing>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListPricingQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPricing>>> = ({ signal }) =>
    listPricing(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPricing>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPricingQueryResult = NonNullable<Awaited<ReturnType<typeof listPricing>>>;
export type ListPricingQueryError = unknown;

export function useListPricing<TData = Awaited<ReturnType<typeof listPricing>>, TError = unknown>(
  params: undefined | ListPricingParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPricing>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPricing>>,
          TError,
          Awaited<ReturnType<typeof listPricing>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListPricing<TData = Awaited<ReturnType<typeof listPricing>>, TError = unknown>(
  params?: ListPricingParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPricing>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPricing>>,
          TError,
          Awaited<ReturnType<typeof listPricing>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListPricing<TData = Awaited<ReturnType<typeof listPricing>>, TError = unknown>(
  params?: ListPricingParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPricing>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 価格一覧を取得する
 */

export function useListPricing<TData = Awaited<ReturnType<typeof listPricing>>, TError = unknown>(
  params?: ListPricingParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPricing>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListPricingQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createPricingResponse201 = {
  data: void;
  status: 201;
};

export type createPricingResponseSuccess = createPricingResponse201 & {
  headers: Headers;
};

export type createPricingResponse = createPricingResponseSuccess;

export const getCreatePricingUrl = () => {
  return `/api/v1/pricings`;
};

/**
 * @summary 価格を作成する
 */
export const createPricing = async (
  createPricingRequest: CreatePricingRequest,
  options?: RequestInit,
): Promise<createPricingResponse> => {
  return apiClient<createPricingResponse>(getCreatePricingUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createPricingRequest),
  });
};

export const getCreatePricingMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPricing>>,
    TError,
    { data: CreatePricingRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPricing>>,
  TError,
  { data: CreatePricingRequest },
  TContext
> => {
  const mutationKey = ["createPricing"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPricing>>,
    { data: CreatePricingRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createPricing(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePricingMutationResult = NonNullable<Awaited<ReturnType<typeof createPricing>>>;
export type CreatePricingMutationBody = CreatePricingRequest;
export type CreatePricingMutationError = unknown;

/**
 * @summary 価格を作成する
 */
export const useCreatePricing = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPricing>>,
      TError,
      { data: CreatePricingRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPricing>>,
  TError,
  { data: CreatePricingRequest },
  TContext
> => {
  return useMutation(getCreatePricingMutationOptions(options), queryClient);
};
