/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ProductsRouteImport } from "./routes/products";
import { Route as CategoriesRouteImport } from "./routes/categories";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProductsNewRouteImport } from "./routes/products_.new";
import { Route as ProductsIdRouteImport } from "./routes/products_.$id";
import { Route as CategoriesNewRouteImport } from "./routes/categories_.new";
import { Route as CategoriesIdRouteImport } from "./routes/categories_.$id";
import { Route as ProductsIdEditRouteImport } from "./routes/products_.$id_.edit";
import { Route as CategoriesIdEditRouteImport } from "./routes/categories_.$id_.edit";

const ProductsRoute = ProductsRouteImport.update({
  id: "/products",
  path: "/products",
  getParentRoute: () => rootRouteImport,
} as any);
const CategoriesRoute = CategoriesRouteImport.update({
  id: "/categories",
  path: "/categories",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: "/products_/new",
  path: "/products/new",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: "/products_/$id",
  path: "/products/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const CategoriesNewRoute = CategoriesNewRouteImport.update({
  id: "/categories_/new",
  path: "/categories/new",
  getParentRoute: () => rootRouteImport,
} as any);
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: "/categories_/$id",
  path: "/categories/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsIdEditRoute = ProductsIdEditRouteImport.update({
  id: "/products_/$id_/edit",
  path: "/products/$id/edit",
  getParentRoute: () => rootRouteImport,
} as any);
const CategoriesIdEditRoute = CategoriesIdEditRouteImport.update({
  id: "/categories_/$id_/edit",
  path: "/categories/$id/edit",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/categories": typeof CategoriesRoute;
  "/products": typeof ProductsRoute;
  "/categories/$id": typeof CategoriesIdRoute;
  "/categories/new": typeof CategoriesNewRoute;
  "/products/$id": typeof ProductsIdRoute;
  "/products/new": typeof ProductsNewRoute;
  "/categories/$id/edit": typeof CategoriesIdEditRoute;
  "/products/$id/edit": typeof ProductsIdEditRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/categories": typeof CategoriesRoute;
  "/products": typeof ProductsRoute;
  "/categories/$id": typeof CategoriesIdRoute;
  "/categories/new": typeof CategoriesNewRoute;
  "/products/$id": typeof ProductsIdRoute;
  "/products/new": typeof ProductsNewRoute;
  "/categories/$id/edit": typeof CategoriesIdEditRoute;
  "/products/$id/edit": typeof ProductsIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/categories": typeof CategoriesRoute;
  "/products": typeof ProductsRoute;
  "/categories_/$id": typeof CategoriesIdRoute;
  "/categories_/new": typeof CategoriesNewRoute;
  "/products_/$id": typeof ProductsIdRoute;
  "/products_/new": typeof ProductsNewRoute;
  "/categories_/$id_/edit": typeof CategoriesIdEditRoute;
  "/products_/$id_/edit": typeof ProductsIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/categories"
    | "/products"
    | "/categories/$id"
    | "/categories/new"
    | "/products/$id"
    | "/products/new"
    | "/categories/$id/edit"
    | "/products/$id/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/categories"
    | "/products"
    | "/categories/$id"
    | "/categories/new"
    | "/products/$id"
    | "/products/new"
    | "/categories/$id/edit"
    | "/products/$id/edit";
  id:
    | "__root__"
    | "/"
    | "/categories"
    | "/products"
    | "/categories_/$id"
    | "/categories_/new"
    | "/products_/$id"
    | "/products_/new"
    | "/categories_/$id_/edit"
    | "/products_/$id_/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CategoriesRoute: typeof CategoriesRoute;
  ProductsRoute: typeof ProductsRoute;
  CategoriesIdRoute: typeof CategoriesIdRoute;
  CategoriesNewRoute: typeof CategoriesNewRoute;
  ProductsIdRoute: typeof ProductsIdRoute;
  ProductsNewRoute: typeof ProductsNewRoute;
  CategoriesIdEditRoute: typeof CategoriesIdEditRoute;
  ProductsIdEditRoute: typeof ProductsIdEditRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/products": {
      id: "/products";
      path: "/products";
      fullPath: "/products";
      preLoaderRoute: typeof ProductsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/categories": {
      id: "/categories";
      path: "/categories";
      fullPath: "/categories";
      preLoaderRoute: typeof CategoriesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products_/new": {
      id: "/products_/new";
      path: "/products/new";
      fullPath: "/products/new";
      preLoaderRoute: typeof ProductsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products_/$id": {
      id: "/products_/$id";
      path: "/products/$id";
      fullPath: "/products/$id";
      preLoaderRoute: typeof ProductsIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/categories_/new": {
      id: "/categories_/new";
      path: "/categories/new";
      fullPath: "/categories/new";
      preLoaderRoute: typeof CategoriesNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/categories_/$id": {
      id: "/categories_/$id";
      path: "/categories/$id";
      fullPath: "/categories/$id";
      preLoaderRoute: typeof CategoriesIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products_/$id_/edit": {
      id: "/products_/$id_/edit";
      path: "/products/$id/edit";
      fullPath: "/products/$id/edit";
      preLoaderRoute: typeof ProductsIdEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/categories_/$id_/edit": {
      id: "/categories_/$id_/edit";
      path: "/categories/$id/edit";
      fullPath: "/categories/$id/edit";
      preLoaderRoute: typeof CategoriesIdEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  ProductsRoute: ProductsRoute,
  CategoriesIdRoute: CategoriesIdRoute,
  CategoriesNewRoute: CategoriesNewRoute,
  ProductsIdRoute: ProductsIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  CategoriesIdEditRoute: CategoriesIdEditRoute,
  ProductsIdEditRoute: ProductsIdEditRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
